/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantjavaapp.view;

import javax.swing.JOptionPane;
import restaurantjavaapp.controller.ControllerUser;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JTable;

/**
 *
 * @author ASUS
 */
public class MenuRegistrasi extends javax.swing.JFrame {

    /**
     * Creates new form MenuMasakan
     */
    public MenuRegistrasi() {
        initComponents();
        setResizable(false);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        this.refreshTable();
    }

    public void refreshTable() {
        //membuat objek
        ControllerUser cu = new ControllerUser();
        DefaultTableModel dtm = cu.buatTabel();

        //menerapkan desain tabel dtm ke tblRegistrasi
        this.tblRegistrasi.setModel(dtm);

        //mengisi tblPasien dengan data
        cu.tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        cmbIdLevel = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrasi = new javax.swing.JTable();
        txtNamaUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtIdUser = new javax.swing.JLabel();
        btnMenuMasakan = new rojerusan.RSMaterialButtonRectangle();
        btnDelete = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate = new rojerusan.RSMaterialButtonRectangle();
        btnInput = new rojerusan.RSMaterialButtonRectangle();
        btnLogout = new rojerusan.RSMaterialButtonRectangle();
        btnClear = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Registrasi");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBorder(null);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 260, 20));

        cmbIdLevel.setBackground(new java.awt.Color(102, 102, 102));
        cmbIdLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbIdLevel.setBorder(null);
        getContentPane().add(cmbIdLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 90, -1));

        tblRegistrasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistrasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistrasi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 532, 220));

        txtNamaUser.setBorder(null);
        getContentPane().add(txtNamaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 260, 20));

        txtPassword.setBorder(null);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 260, 20));
        getContentPane().add(txtIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 160, -1));

        btnMenuMasakan.setBackground(new java.awt.Color(0, 102, 255));
        btnMenuMasakan.setText("MENU RESTO");
        btnMenuMasakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMasakanActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuMasakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 167, 50));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 104, 50));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 104, 50));

        btnInput.setText("INPUT");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 108, 50));

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 104, 50));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 108, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantjavaapp/assets/DesainMenuRegistrasi.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRegistrasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrasiMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Konversi tblresigtrasi ke DTM
        DefaultTableModel dtm2 = (DefaultTableModel) tblRegistrasi.getModel();

        //mengambil 1 baris data yang diklik
        int pilih = tblRegistrasi.getSelectedRow();

        //masukkkan ke text field
        //pilih --> Baris, angka --> kolom
        this.txtIdUser.setText(dtm2.getValueAt(pilih, 0).toString());
        this.txtUsername.setText(dtm2.getValueAt(pilih, 1).toString());
        this.txtPassword.setText(dtm2.getValueAt(pilih, 2).toString());
        this.txtNamaUser.setText(dtm2.getValueAt(pilih, 3).toString());
        this.cmbIdLevel.setSelectedItem(dtm2.getValueAt(pilih, 4).toString());
    }//GEN-LAST:event_tblRegistrasiMouseClicked

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        String username = this.txtUsername.getText().trim();
        String password = this.txtPassword.getText().trim();
        String namaUser = this.txtNamaUser.getText().trim();
        String idLevel = (String) this.cmbIdLevel.getSelectedItem();

        if (username.isEmpty() || password.isEmpty() || namaUser.isEmpty() || idLevel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses jika ada field kosong
        }

        // Proses input data ke Controller
        ControllerUser cu = new ControllerUser();
        boolean status = cu.tambahData(username, password, namaUser, Integer.parseInt(idLevel));

        if (status) {
            this.refreshTable();
            JOptionPane.showMessageDialog(this, "Berhasil Tambah Data");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Tambah Data");
        }

    }//GEN-LAST:event_btnInputActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        ControllerUser cu = new ControllerUser();
        int idUser = Integer.parseInt(this.txtIdUser.getText());
        boolean status = cu.hapusData(idUser);

        if (status == true) {
            this.refreshTable();
            JOptionPane.showMessageDialog(this, "Berhasil Hapus Data");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Hapus Data");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String idUser = this.txtIdUser.getText().trim();
        String username = this.txtUsername.getText().trim();
        String password = this.txtPassword.getText().trim();
        String namaUser = this.txtNamaUser.getText().trim();
        String idLevel = (String) this.cmbIdLevel.getSelectedItem();

        if (idUser.isEmpty() || username.isEmpty() || password.isEmpty() || namaUser.isEmpty() || idLevel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses jika ada field kosong
        }

        // Proses update data ke Controller
        ControllerUser cu = new ControllerUser();
        boolean status = cu.ubahData(Integer.parseInt(idUser), username, password, namaUser, Integer.parseInt(idLevel));

        if (status) {
            this.refreshTable();
            JOptionPane.showMessageDialog(this, "Berhasil Update Data");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Update Data");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnMenuMasakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMasakanActionPerformed
        // TODO add your handling code here:
        MenuRestoran masak = new MenuRestoran();
        masak.setVisible(true);
        this.setVisible(false);
        masak.btnInput.setEnabled(true);
        masak.btnDelete.setEnabled(true);
        masak.btnUpdate.setEnabled(true);
        masak.btnTransaksi.setEnabled(true);
        masak.btnLogout.setEnabled(true);
    }//GEN-LAST:event_btnMenuMasakanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.txtIdUser.setText("");
        this.txtNamaUser.setText("");
        this.txtPassword.setText("");
        this.txtUsername.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FormLogin fl = new FormLogin();
        fl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRegistrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojerusan.RSMaterialButtonRectangle btnClear;
    public rojerusan.RSMaterialButtonRectangle btnDelete;
    public rojerusan.RSMaterialButtonRectangle btnInput;
    public rojerusan.RSMaterialButtonRectangle btnLogout;
    public rojerusan.RSMaterialButtonRectangle btnMenuMasakan;
    public rojerusan.RSMaterialButtonRectangle btnUpdate;
    private javax.swing.JComboBox<String> cmbIdLevel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistrasi;
    private javax.swing.JLabel txtIdUser;
    private javax.swing.JTextField txtNamaUser;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
