/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantjavaapp.view;

import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import restaurantjavaapp.controller.ControllerTransaksi;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JLabel;
import restaurantjavaapp.model.Session;

/**
 *
 * @author ASUS
 */
public class MenuTransaksi extends javax.swing.JFrame {

    ControllerTransaksi controller;
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    public String sql;

    private int idUser;
    private String namaUser;

    public JComboBox<String> getCmbIdMenu() {
        return cmbIdMenu;
    }

    public JTable getTblTransaksi() {
        return tblTransaksi;
    }

    public JLabel getTxtIdTransaksi() {
        return txtIdTransaksi;
    }

    public JTextField getTxtJmlBeli() {
        return txtJmlBeli;
    }

    public JTextField getTxtNamaPelanggan() {
        return txtNamaPelanggan;
    }

    public JDateChooser getTxtTanggal() {
        return txtTanggal;
    }

    public JLabel getTxtTotalBayar() {
        return txtTotalBayar;
    }

    /**
     * Creates new form MenuMasakan
     */
    public MenuTransaksi() {
        initComponents();
        // mengambil ukuran layar
        setResizable(false);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        this.refreshTable();

        int lvl = Session.getLvlsekarang();
        switch (lvl) {
            case 1:

                this.btnCetakLaporan1.setEnabled(true);
                this.btnMenuRegistrasi.setEnabled(true);
                break;

            case 3:

                this.btnCetakLaporan1.setEnabled(true);
                break;
        }
    }

    public MenuTransaksi(int a, String b) {
        initComponents();
        this.idUser = a;
        this.namaUser = b;
        setResizable(false);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        refreshTable();
        
        int lvl = Session.getLvlsekarang();
        switch (lvl) {
            case 1:

                this.btnCetakLaporan1.setEnabled(true);
                this.btnMenuRegistrasi.setEnabled(true);
                break;

            case 3:

                this.btnCetakLaporan1.setEnabled(true);
                break;
        }
    }

    public int getIdUser() {
        return idUser;
    }

    public String getNamaUser() {
        return namaUser;
    }

    public void refreshTable() {
        ControllerTransaksi ct = new ControllerTransaksi();
        DefaultTableModel dtm = ct.buatTabel();

        this.tblTransaksi.setModel(dtm);

        ct.tampilkanData(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNamaPelanggan = new javax.swing.JTextField();
        cmbIdMenu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        txtJmlBeli = new javax.swing.JTextField();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        txtIdTransaksi = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JLabel();
        btnCetakLaporan1 = new rojerusan.RSMaterialButtonRectangle();
        btnInput = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate = new rojerusan.RSMaterialButtonRectangle();
        btnDelete = new rojerusan.RSMaterialButtonRectangle();
        btnClear = new rojerusan.RSMaterialButtonRectangle();
        btnMenuRegistrasi = new rojerusan.RSMaterialButtonRectangle();
        btnLogout = new rojerusan.RSMaterialButtonRectangle();
        btnMenuMasakan = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MenuTransaksi");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaPelanggan.setBorder(null);
        getContentPane().add(txtNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 260, 20));

        cmbIdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdMenuActionPerformed(evt);
            }
        });
        getContentPane().add(cmbIdMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 170, 30));

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 940, 210));

        txtJmlBeli.setBorder(null);
        getContentPane().add(txtJmlBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 324, 270, 20));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 280, 30));
        getContentPane().add(txtIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 70, -1));
        getContentPane().add(txtTotalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 250, 20));

        btnCetakLaporan1.setBackground(new java.awt.Color(0, 102, 0));
        btnCetakLaporan1.setText("CETAK LAPORAN");
        btnCetakLaporan1.setEnabled(false);
        btnCetakLaporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakLaporan1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetakLaporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 180, 50));

        btnInput.setText("INPUT");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 180, 50));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 180, 50));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 180, 50));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 40));

        btnMenuRegistrasi.setText("MENU REGISTRASI");
        btnMenuRegistrasi.setEnabled(false);
        btnMenuRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegistrasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuRegistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 40));

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 130, 40));

        btnMenuMasakan.setText("LIHAT MENU");
        btnMenuMasakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMasakanActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuMasakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 110, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantjavaapp/assets/MenuTransaksi.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIdMenuActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm4 = (DefaultTableModel) tblTransaksi.getModel();

        // Mengambil 1 baris data yang diklik
        int pilih = tblTransaksi.getSelectedRow();

        if (pilih != -1) { // memastikan bariss
            // Set ID Transaksi
            this.txtIdTransaksi.setText(dtm4.getValueAt(pilih, 0).toString());

            // Set Nama Pelanggan
            this.txtNamaPelanggan.setText(dtm4.getValueAt(pilih, 3).toString());

            // sset ID Menu
            String menuItem = dtm4.getValueAt(pilih, 4).toString();
            for (int i = 0; i < cmbIdMenu.getItemCount(); i++) {
                if (cmbIdMenu.getItemAt(i).contains(menuItem)) {
                    cmbIdMenu.setSelectedItem(cmbIdMenu.getItemAt(i));
                    break;
                }
            }

            // Set Tanggal
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date date = sdf.parse(dtm4.getValueAt(pilih, 5).toString());
                this.txtTanggal.setDate(date);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal memuat tanggal: " + e.getMessage());
            }

            // Set Jumlah Beli
            this.txtJmlBeli.setText(dtm4.getValueAt(pilih, 9).toString());

            // Set Total Bayar
            this.txtTotalBayar.setText(dtm4.getValueAt(pilih, 10).toString());
        }
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void btnCetakLaporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakLaporan1ActionPerformed
        // TODO add your handling code here:
        ControllerTransaksi ct = new ControllerTransaksi();
        ct.cetakLaporan();
    }//GEN-LAST:event_btnCetakLaporan1ActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        controller = new ControllerTransaksi();
        controller.prosesTransaksi(this);
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller = new ControllerTransaksi();
        controller.prosesUbahTransaksi(this);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller = new ControllerTransaksi();
        controller.prosesDeleteTransaksi(this);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.txtIdTransaksi.setText("");
        this.txtJmlBeli.setText("");
        this.txtNamaPelanggan.setText("");
        this.txtTanggal.setDate(null);
        this.txtTotalBayar.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMenuRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegistrasiActionPerformed
        // TODO add your handling code here:
        MenuRegistrasi mr = new MenuRegistrasi();
        mr.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnMenuRegistrasiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FormLogin fl = new FormLogin();
        fl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMenuMasakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMasakanActionPerformed
        // TODO add your handling code here:
        MenuRestoran mr = new MenuRestoran();
        mr.setVisible(true);
        this.setVisible(false);
        mr.btnDelete.setEnabled(true);
        mr.btnInput.setEnabled(true);
        mr.btnLogout.setEnabled(true);
        mr.btnUpdate.setEnabled(true);
        mr.btnTransaksi.setEnabled(true);
    }//GEN-LAST:event_btnMenuMasakanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojerusan.RSMaterialButtonRectangle btnCetakLaporan1;
    public rojerusan.RSMaterialButtonRectangle btnClear;
    public rojerusan.RSMaterialButtonRectangle btnDelete;
    public rojerusan.RSMaterialButtonRectangle btnInput;
    public rojerusan.RSMaterialButtonRectangle btnLogout;
    private rojerusan.RSMaterialButtonRectangle btnMenuMasakan;
    public rojerusan.RSMaterialButtonRectangle btnMenuRegistrasi;
    public rojerusan.RSMaterialButtonRectangle btnUpdate;
    private javax.swing.JComboBox<String> cmbIdMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JLabel txtIdTransaksi;
    private javax.swing.JTextField txtJmlBeli;
    private javax.swing.JTextField txtNamaPelanggan;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JLabel txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
