/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantjavaapp.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurantjavaapp.controller.ControllerMenuResto;
import java.awt.Dimension;
import java.awt.Toolkit;
import restaurantjavaapp.model.Session;

/**
 *
 * @author ASUS
 */
public class MenuRestoran extends javax.swing.JFrame {

    /**
     * Creates new form MenuMasakan
     */
    public MenuRestoran() {
        initComponents();
        setResizable(false);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        int lvl = Session.getLvlsekarang();
        if (lvl == 1) {
            this.btnRegistrasi.setEnabled(true);
        } else {
            this.btnRegistrasi.setEnabled(false);
        }
        this.refreshTable();

    }

    public void refreshTable() {
        ControllerMenuResto cm = new ControllerMenuResto();
        DefaultTableModel dtm = cm.buatTabel();

        this.tblResto.setModel(dtm);

        cm.tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNamaMenu = new javax.swing.JTextField();
        txtHargaMenu = new javax.swing.JTextField();
        cmbStatusMenu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResto = new javax.swing.JTable();
        cmbKategori = new javax.swing.JComboBox<>();
        txtIdMenu = new javax.swing.JLabel();
        btnRegistrasi = new rojerusan.RSMaterialButtonRectangle();
        btnInput = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate = new rojerusan.RSMaterialButtonRectangle();
        btnDelete = new rojerusan.RSMaterialButtonRectangle();
        btnLogout = new rojerusan.RSMaterialButtonRectangle();
        btnClear = new rojerusan.RSMaterialButtonRectangle();
        btnTransaksi = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Resto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaMenu.setBorder(null);
        getContentPane().add(txtNamaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 260, 20));

        txtHargaMenu.setBorder(null);
        txtHargaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaMenuActionPerformed(evt);
            }
        });
        getContentPane().add(txtHargaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 206, 260, 20));

        cmbStatusMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERSEDIA", "HABIS" }));
        cmbStatusMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusMenuActionPerformed(evt);
            }
        });
        getContentPane().add(cmbStatusMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 280, 30));

        tblResto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRestoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 530, 260));

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAKANAN", "MINUMAN" }));
        cmbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(cmbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 280, 30));
        getContentPane().add(txtIdMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 150, 20));

        btnRegistrasi.setText("MENU REGISTRASI");
        btnRegistrasi.setEnabled(false);
        btnRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 170, 50));

        btnInput.setText("INPUT");
        btnInput.setEnabled(false);
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 110, 50));

        btnUpdate.setText("UPDATE");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 120, 50));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("DELETE");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 110, 50));

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 110, 50));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 110, 50));

        btnTransaksi.setText("MENU TRANSAKSI");
        btnTransaksi.setEnabled(false);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 150, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantjavaapp/assets/DesainMenuResto.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaMenuActionPerformed

    private void tblRestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRestoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm3 = (DefaultTableModel) tblResto.getModel();

        int select = tblResto.getSelectedRow();

        this.txtIdMenu.setText(dtm3.getValueAt(select, 0).toString());
        this.txtNamaMenu.setText(dtm3.getValueAt(select, 1).toString());
        this.txtHargaMenu.setText(dtm3.getValueAt(select, 2).toString());
        this.cmbStatusMenu.setSelectedItem(dtm3.getValueAt(select, 3).toString());
        this.cmbKategori.setSelectedItem(dtm3.getValueAt(select, 4).toString());
    }//GEN-LAST:event_tblRestoMouseClicked

    private void cmbStatusMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusMenuActionPerformed

    private void cmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKategoriActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        ControllerMenuResto cmr = new ControllerMenuResto();

        String namaMenu = txtNamaMenu.getText();
        String hargaMenuText = txtHargaMenu.getText();
        String statusMenu = (String) cmbStatusMenu.getSelectedItem();
        String kategoriMenu = (String) cmbKategori.getSelectedItem();

        if (namaMenu.isEmpty() || hargaMenuText.isEmpty() || statusMenu == null || kategoriMenu == null) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int hargaMenu = 0;
        try {
            hargaMenu = Integer.parseInt(hargaMenuText);
            if (hargaMenu <= 0) {
                JOptionPane.showMessageDialog(this, "Harga menu harus lebih besar dari 0!", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga menu harus berupa angka!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean status = cmr.tambahData(namaMenu, hargaMenu, statusMenu, kategoriMenu);

        if (status) {
            this.refreshTable();
            JOptionPane.showMessageDialog(this, "Berhasil Menambah Data Menu");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Menambah Data Menu");
        }

    }//GEN-LAST:event_btnInputActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        ControllerMenuResto cmr = new ControllerMenuResto();
        String idMenuText = txtIdMenu.getText();
        String namaMenu = txtNamaMenu.getText();
        String hargaMenuText = txtHargaMenu.getText();
        String statusMenu = (String) cmbStatusMenu.getSelectedItem();
        String kategoriMenu = (String) cmbKategori.getSelectedItem();

        if (idMenuText.isEmpty() || namaMenu.isEmpty() || hargaMenuText.isEmpty() || statusMenu == null || kategoriMenu == null) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idMenu = 0;
        try {
            idMenu = Integer.parseInt(idMenuText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Menu harus berupa angka!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int hargaMenu = 0;
        try {
            hargaMenu = Integer.parseInt(hargaMenuText);
            if (hargaMenu <= 0) {
                JOptionPane.showMessageDialog(this, "Harga menu harus lebih besar dari 0!", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga menu harus berupa angka!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean status = cmr.ubahData(idMenu, namaMenu, hargaMenu, statusMenu, kategoriMenu);

        if (status) {
            this.refreshTable();
            JOptionPane.showMessageDialog(this, "Berhasil Mengubah Data Menu");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Mengubah Data Menu");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        ControllerMenuResto cmr = new ControllerMenuResto();
        int a = Integer.parseInt(txtIdMenu.getText());

        boolean status = cmr.hapusData(a);

        if (status == true) {
            this.refreshTable();
            JOptionPane.showMessageDialog(this, "Berhasil Menghapus Data Menu");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Menghapus Data Menu");
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiActionPerformed
        // TODO add your handling code here:
        MenuRegistrasi registrasi = new MenuRegistrasi();
        registrasi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrasiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FormLogin fl = new FormLogin();
        fl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.txtIdMenu.setText("");
        this.txtNamaMenu.setText("");
        this.txtHargaMenu.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        MenuTransaksi mt = new MenuTransaksi();
        mt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRestoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojerusan.RSMaterialButtonRectangle btnClear;
    public rojerusan.RSMaterialButtonRectangle btnDelete;
    public rojerusan.RSMaterialButtonRectangle btnInput;
    public rojerusan.RSMaterialButtonRectangle btnLogout;
    public rojerusan.RSMaterialButtonRectangle btnRegistrasi;
    public rojerusan.RSMaterialButtonRectangle btnTransaksi;
    public rojerusan.RSMaterialButtonRectangle btnUpdate;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbStatusMenu;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResto;
    private javax.swing.JTextField txtHargaMenu;
    private javax.swing.JLabel txtIdMenu;
    private javax.swing.JTextField txtNamaMenu;
    // End of variables declaration//GEN-END:variables
}
